### ISSUE TITLE
Deprecated install command

### ISSUE THREAD

**Issue by jcorporation** [joshkunz/fakelib#9]
First: cool utility! I use it to do performance testing of my mpd client.

The installation command `go get -u github.com/joshkunz/fakelib` is deprecated.
Please replace it in README with `go install github.com/joshkunz/fakelib@latest`

**Comment by joshkunz** [comment]
> First: cool utility! I use it to do performance testing of my mpd client.

Haha Awesome! I'm glad somebody else found this weird piece of software useful.

Thanks for the FYI, I've pushed a fix.
